/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rating;



import java.util.List;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String args [] ) {
        ApplicationContext context = new ClassPathXmlApplicationContext("springbean.xml");
        
        System.out.println("User");
        User user =(User) context.getBean("user");
        System.out.println("Username     :" +user.getUsername());
    	System.out.println("Email        : "+user.getEmailid());
    	System.out.println("Password        : "+user.getPassword());
    	System.out.println("Mobile Number   : "+user.getMobilenumber());
    	System.out.println("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_");
    	
    	System.out.println("Product");
    	Financialproduct fp = (Financialproduct) context.getBean("financialproduct");
    	System.out.println("Product Id    = " +fp.getFinancial_productid());
    	System.out.println("Product Name  = "+fp.getFinancial_product_name());
    	System.out.println("Description   = "+fp.getDescription());
    	System.out.println("Rating        = "+fp.getRating());
    	System.out.println("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_");
    	
    	System.out.println("Review");
    	Review review = (Review) context.getBean("review");
    	System.out.println("Review Id       = "+review.getReviewid());
    	System.out.println("Review Text     = "+review.getReview_text());
    	List<Comment> comments = review.getComments();
    	System.out.println("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_");
    	
    	System.out.println("Comments");
    	for(Comment c:comments) {
    		System.out.println("Id         = "+c.getComment_id());
    		System.out.println("Text       = "+c.getComment_text());
    		System.out.println("Likes       = "+c.getLikes());
    		System.out.println("Dislikes    = "+c.getDislikes());
    		System.out.println("Report      = "+c.isReport());
    		System.out.println("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_");
    	}
    	
        }
}
